apiVersion: apps/v1
kind: Deployment
metadata:
  name: hw-deploy
  labels:
    app: homework
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homework
  template:
    metadata:
      labels:
        app: homework
    spec:
      containers:
      - name: homework
        image: tonktawork
        ports:
        - containerPort: 80
