apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    app: {{ .Values.labels.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.labels.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels.name }}
    spec:
      containers:
      - name: homework
        image: "{{ .Values.image }}:{{ .Values.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
