# This is a basic workflow to help you get started with Actions

name: myhomework

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ homework ]
  pull_request:
    branches: [ homework ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: build Dockerfile
        run: docker build -t myapp .

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: deploy app with docker
        run: docker run -d -p 80:80 myapp 
  check:
    needs: deploy
    runs-on: self-hosted
    steps:
      - name: check curl
        run: HTTP_RESULT=$(curl -i localhost:80 2>/dev/null |grep HTTP|awk '{print $2}' ); if [ "$HTTP_RESULT" = '200' ];then echo "deployed successful";exit 0; else echo "deployed failed";exit 255;fi
